ISSUE-114-115 accountid not updated, failure on missing project.yaml
ISSUE-115 Fixed scenario when project.yaml does not exist but build.env does

ISSUE-115 Added doc on how to create a test package and improved the ver auto gen for test

ISSUE-115 Fixed build.env creation so it is located always in the project root dir

ISSUE-114 Fixed release-drafter action

ISSUE-114 Fixed release-drafter action, triggers

ISSUE-114-115 If no project.yaml or build.env read short-name from common.tfvars

ISSUE-87 Removed triggers on pull_request events

ISSUE-117 Fixed "IDs stored as int instead of text"

ISSUE-117 Fixed test deploy pipeline

ISSUE-114 removed escaped char

ISSUE-87 Copied release drafter files from refarch

diff --git a/.github/workflows/build-push-test-package.yml b/.github/workflows/build-push-test-package.yml
--- a/.github/workflows/build-push-test-package.yml
+++ b/.github/workflows/build-push-test-package.yml
@@ -33,10 +33,12 @@ jobs:
             echo "[INFO] Get latest version from TestPypi." && \
             LATEST_VERSION=$(curl -sL "https://test.pypi.org/pypi/leverage/json" | jq -r ".releases | keys | sort | .[-1]") && \
             echo "[INFO] Latest version: $LATEST_VERSION" && \
-            RELEASE_VERSION=$(echo $LATEST_VERSION | awk 'BEGIN{FS="."; OFS="."} {print $1,$2,$3+1}')
+            RELEASE_VERSION="$(echo $LATEST_VERSION | awk 'BEGIN{FS="."; OFS="."} {print $1,$2,$3+1}')rc.1"
 
+          echo "[INFO] Checking Release Version (template 9.9.9-rc9)..."
+          ([ $(echo $RELEASE_VERSION | grep -oP "([0-9]*\.[0-9]*\.[0-9]*\-rc[0-9]+)") ] && echo "[INFO] Version ok" ) || (echo "[ERROR] Version is wrong" && exit 1)
           echo "[INFO] Bump version to $RELEASE_VERSION"
-          sed -i s/$CURRENT_VERSION/$RELEASE_VERSION/ $INIT_FILE
+          sed -i 's/'$CURRENT_VERSION'/'$RELEASE_VERSION'/' $INIT_FILE
         env:
           INIT_FILE: leverage/__init__.py
           RELEASE_VERSION: ${{ github.event.inputs.version }}
