Issue 141 - all-layers, s3 key multi region support and others (#149)
* ISSUE-141 Added multi options for s3 key checking

* ISSUE-141 Improved way to check DR

* ISSUE-1 added multi region support, tfautomv, s3 key autogeneration, layer region autodetection, region fallback system (layer dir, then account tfvars, then project tfvars)

* ISSUE-141 adding path to deploy beta and alpha images

* ISSUE-141 fixed python version

* ISSUE-141 added region var to tf command line; fixed var name in credentials

* ISSUE-141 set toolbox version

* ISSUE-141 imported tests from master

* ISSUE-141 fix to _find_region function

* Update leverage/container.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* Update leverage/container.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* Update leverage/container.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* Update leverage/modules/terraform.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* Issue 123 all layers option (#151)

* ISSUE-123 added logic for init-multi command

* ISSUE-123 all terraform commands keeps running on layers but accept --layers list to run from account level

* ISSUE-141 persist s3 key when dynamically generated

* ISSUE-123 added logic for recording the s3 key in the tf file when automagically generated; removed hidden commands from tf commands

* Update leverage/container.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* ISSUE-123 changed internal functions from click commands to regular functions; code refactor for sake of readability

* ISSUE-123 fixed test

* ISSUE-123 fixed makefile for testing

* Update leverage/container.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* Update leverage/container.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* Update leverage/modules/terraform.py

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* ISSUE-123 fixed comments for PR 151

* ISSUE-123 removed comments

* ISSUE-123 fixed condition

* ISSUE-123 changed value sublayer to layers_group

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

* ISSUE-141 toolbox version updated

Co-authored-by: Angelo Fenoglio <angelofenoglio@gmail.com>

diff --git a/.github/workflows/build-push-test-package.yml b/.github/workflows/build-push-test-package.yml
--- a/.github/workflows/build-push-test-package.yml
+++ b/.github/workflows/build-push-test-package.yml
@@ -17,6 +17,8 @@ jobs:
       - uses: actions/checkout@v2
 
       - uses: actions/setup-python@v2
+        with:
+          python-version: '3.8'
 
       - name: install_dependencies
         run: |
@@ -36,7 +38,7 @@ jobs:
             RELEASE_VERSION="$(echo $LATEST_VERSION | awk 'BEGIN{FS="."; OFS="."} {print $1,$2,$3+1}')rc.1"
 
           echo "[INFO] Checking Release Version (template 9.9.9-rc9)..."
-          ([ $(echo $RELEASE_VERSION | grep -oP "([0-9]*\.[0-9]*\.[0-9]*\-rc[0-9]+)") ] && echo "[INFO] Version ok" ) || (echo "[ERROR] Version is wrong" && exit 1)
+          ([ $(echo $RELEASE_VERSION | grep -oP "([0-9]*\.[0-9]*\.[0-9]*\-(rc|alpha|beta)[0-9]+)") ] && echo "[INFO] Version ok" ) || (echo "[ERROR] Version is wrong" && exit 1)
           echo "[INFO] Bump version to $RELEASE_VERSION"
           sed -i 's/'$CURRENT_VERSION'/'$RELEASE_VERSION'/' $INIT_FILE
         env:
